### ISSUE TITLE
Experimenting with a custom test file

### ISSUE THREAD

**Issue by assaftibm** [shrimai/Topological-Sort-for-Sentence-Ordering#3]
Hi,
Thanks for this great work.

I'm trying to use one of the trained models to predict the order of N sentences that come from independent sources.  There is no ground-truth for the ordering, and I just want to obtain the predictions from the model to construct a document based on on the predicted order of sentences. 

I'd appreciate your help with some difficulties that I have.

I created a a test file in this format:

```id \t sentence1 \t sentence2 \t label \t index_of_sentence1_in_document \t index_of_sentence2_in_document```

I set `index_of_sentence1_in_document` to 0, and `index_of_sentence2_in_document`  to 1, and I assume that this has no influence on the predictions.

Question 1: is the test file supposed to include all possible combinations of two sentences from the N sentences that I have? 

After running the model, I got a results file, with the new columns of logits and prediction label, and now I'd like to use the topological sort to predict the global order of the sentences.

However, when I try to run the sort as suggested [here](https://github.com/shrimai/Topological-Sort-for-Sentence-Ordering#topological-sort), I get an error in line 187:
```
    docid, nvert, npairs = ids.split('-')
ValueError: not enough values to unpack (expected 3, got 1)
```
This makes sense because the `ids` variable is an integer, not a string with dashes that can be split into 3 parts.

Question 2: does that mean that my original test file should include a triplet in the id column? 

Could you please help with this?

Thanks!

**Comment by shrimai** [comment]
Hi,
>Question 1: is the test file supposed to include all possible combinations of two sentences from the N sentences that I have?

Yes, you need to include all (N choose 2) combinations of pairs of sentences in your test file to get predictions for each pair.

>Question 2: does that mean that my original test file should include a triplet in the id column?

Yes, you need to know how many pairs of sentences belong to each document. I had multiple documents in my test set, hence I used  ```docid, nvert, npairs``` to indicate the document id, number of vertices (equal to number of sentences) in the document and number of pairs (N choose 2). This was done to give an idea of how many future lines belong to the current document and should be added to the current graph ([here](https://github.com/shrimai/Topological-Sort-for-Sentence-Ordering/blob/ac73e5ef1d49c5fd8b8ac31817bd294ef1f0a477/topological_sort.py#L194)). If you have only one document in your file then you will not need these. If you have multiple documents then yes, you need triplets in the form doc_id-nver-npairs.

**Comment by assaftibm** [comment]
Thanks.
If I have sentences from multiple documents, and I use the  `docid-nvert-npairs` pattern in the `id` column of my input tsv file, since docid, nvert and npairs are constants for the same doc,  I get that all sentences from the same doc have the same id. This means that the id column isn't unique per example. Isn't that a problem for the bert-based classifier?

**Comment by assaftibm** [comment]
I tried to continue and have two more questions:

1 - When I run the topological search on the result file, I see that it uses the values from the `pos_a` and `pos_b` columns in the graph construction (line 197 - `pos_s1, pos_s2 = int(data[j][4]), int(data[j][5])`). It seems like these values are used as vertices ids. Is that means that I need to use a unique pos value for every sentence from the same document? like, enumerating them from 0 to N?

2 - to get the result of the sort for each document, should I print the variable `order` after it is assigned a value in line 209? 
```
        order = g.topologicalSort()
```

Thanks again!

**Comment by shrimai** [comment]
>This means that the id column isn't unique per example. Isn't that a problem for the bert-based classifier?

You are right. All the examples of the same doc don't have unique id. This has not been a problem fo me when I used the 2.3.0 version of transformers lib. If you are using a different version then you can check how they process the InputExample, [this line](https://github.com/shrimai/Topological-Sort-for-Sentence-Ordering/blob/ac73e5ef1d49c5fd8b8ac31817bd294ef1f0a477/bert_classifier/model.py#L521-L522). 

> Is that means that I need to use a unique pos value for every sentence from the same document? like, enumerating them from 0 to N?

Yes, exactly. You have to just enumerate sentences in a document and whether sentence3 will come before sentence5 would be decided by the classifier prediction. So Line 197 tells which of the two sentences was first while asking the classifier. This is because while creating the file one of the two sentences was randomly chosen to be first ([here](https://github.com/shrimai/Topological-Sort-for-Sentence-Ordering/blob/ac73e5ef1d49c5fd8b8ac31817bd294ef1f0a477/prepare_data.py#L103-L108)). An example to clarify this:
If you had a document (doc_id=1) with 4 sentences: s1, s2, s3, s4. Then you have 6 pairs of sentences and the input file looks like (sentence index starts from 0):

doc_id-nvert-npairs \t sentence1 \t sentences2 \t label \t pos_sentence1 \t pos_sentence2
1-4-6 \t s2 \t s1 \t 0 \t 1 \t 0  # Randomly choosing s2 to be first and asking classifier if s2 precedes s1
1-4-6 \t s1 \t s3 \t 1 \t 0 \t 2  # Randomly choosing s1 to be first and asking classifier if s1 precedes s3
1-4-6 \t s4 \t s1 \t 0 \t 3 \t 0
1-4-6 \t s2 \t s3 \t 1 \t 1 \t 2
1-4-6 \t s4 \t s2 \t 0 \t 3 \t 1
1-4-6 \t s3 \t s4 \t 1 \t 2 \t 3

If you don't have ground truth labels then you can leave them as 0. This was necessary only to calculate the metrics.

>2 - to get the result of the sort for each document, should I print the variable order after it is assigned a value in line 209?

Yes, you don't have to calculate the metric. You can skip the update stats part and only print the orders after line 209.

**Comment by shrimai** [comment]
You can use [this](https://github.com/shrimai/Topological-Sort-for-Sentence-Ordering/blob/ac73e5ef1d49c5fd8b8ac31817bd294ef1f0a477/prepare_data.py#L130-L160) fn to write an input file for your data. You will have to change [this](https://github.com/shrimai/Topological-Sort-for-Sentence-Ordering/blob/ac73e5ef1d49c5fd8b8ac31817bd294ef1f0a477/prepare_data.py#L123-L128) part to load your documents (```Line 123```)and have documents as a list of sentences(```Line 128```). You can copy and modify that function to suit your data loading.

**Comment by assaftibm** [comment]
Many thanks, I think I got the point.
